datamodule:
  tasks: semseg,human_parts,sal,normals,edge
  dataset_name: PASCALContext
  batch_size: 8  # in total
  num_workers: 4  # per GPU

model:
  model_backbone: HRNet18-S
  model_head: AdaptiveTaskRelationalContextSearchHead
  in_index: 0,1,2,3
  iterations: 40000
  lr: 0.005
  weight_decay: 0.0005

trainer:
  sync_batchnorm: True
  check_val_every_n_epoch: 3
  gradient_clip_val: 10